url: "https://frostphyr.com"
permalink: pretty
exclude: ["downloads"]
plugins:
  - jekyll-sitemap
  - liquid-arrays
  - jekyll-php
exclude:
  - "*.code-workspace"

defaults:
  - scope:
      path: avail/java
    values:
      project: avail
  - scope:
      path: liquid-arrays
    values:
      project: liquid-arrays
  - scope:
      path: jekyll-php
    values:
      project: jekyll-php
  - scope:
      path: kin-event-keyer
    values:
      project: kin-event-keyer