permalink: pretty
exclude: ["downloads"]

defaults:
  - scope:
      path: "avail/java"
    values:
      project-id: 0
      license-name: Apache License 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0
      maven-groupId: com.frostphyr
      maven-artifactId: avail
  - scope:
      path: "custom-appender"
    values:
      project-id: 1
      license-name: Apache License 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0
      maven-groupId: com.frostphyr
      maven-artifactId: customappender
  - scope:
      path: "kin-event-keyer"
    values:
      project-id: 2
  - scope:
      path: ""
    values:
      projects:
        - name: Avail
          url: /avail/java
          description: Library of general-purpose utilities
          github-url: https://github.com/Frostphyr/avail-java
          project-items:
            - name: Overview
              url: /avail/java
            - generated: true
              url: avail/avail-latest-docs.html
              subitems:
                - generated : true
                  url: avail/avail-docs.html
                - name: All releases
                  url: /avail/java/releases
            - name: Download
              url: /avail/java/releases/download
              subitems:
                - generated : true
                  url: avail/avail-download.html
                - name: All releases
                  url: /avail/java/releases
        - name: CustomAppender
          url: /custom-appender
          description: Log however you want with Log4j2.
          github-url: https://github.com/Frostphyr/CustomAppender
          project-items:
            - name: Overview
              url: /custom-appender
            - name: Manual
              url: /custom-appender/manual
            - name: Download
              url: /custom-appender/releases/download
              subitems:
                - generated: true
                  url: custom-appender-download.html
                - name: All releases
                  url: /custom-appender/releases
        - name: KIN Event Keyer
          url: /kin-event-keyer
          description: Automates the process of keying in events to KIN (Kmart Information Network).
          github-url: https://github.com/Frostphyr/KIN-Event-Keyer
          download-content: kek-download.php
          download-type: jar
          key-database: kin_event_keyer
          project-items:
            - name: Overview
              url: /kin-event-keyer
            - name: Manual
              url: /kin-event-keyer/manual
            - name: Download
              url: /kin-event-keyer/releases/download