permalink: pretty
exclude: ["downloads"]
plugins:
  - liquid-arrays

defaults:
  - scope:
      path: "avail/java"
    values:
      project: avail
  - scope:
      path: "kin-event-keyer"
    values:
      project: kin-event-keyer
  - scope:
      path: "avail/java/download"
    values:
      layout: avail-download
      title: Download {{ page.version }} | Avail
  - scope:
      path: "kin-event-keyer/download"
    values:
      layout: kek-download
      title: Download {{ page.version }} | KIN Event Keyer